### ISSUE TITLE
Docker support

### ISSUE THREAD

**Issue by simonpfeifhofer** [KissG549/InterProcessCommunication#1]
@KissG549:

Would it be possible to add containerization?
It would be great to be able to use docker-compose to start a server and a client. 
If you feel more comfortable with kubernetes it would be even better.

**Comment by KissG549** [comment]
@simonpfeifhofer 

Good idea, I will implement the feature in the next few days.

**Comment by KissG549** [comment]
@simonpfeifhofer 
Docker-compose support has been implemented on master.
Would you be able to provide feedback about the change?
